### PR TITLE
OpenGL output stage with dithering

### PR DESCRIPTION
**Pull request by laurimyllari**
These changes add a separate output stage to the GLSL renderer. It is implemented as a shader that calls process() to allow attaching it to the final pass shader.

RGB range conversion is moved to the output stage to avoid banding. This could be optimized later for the single pass case where it can be done as part of the YUV2RGB conversion.

Dithering is added to the output stage. User settings are provided to disable dithering and to select destination bit depth. Low bit depths are useful for testing to see that dithering is applied correctly. 8bit depth should provide best results for normal use.

This code has been tested with software decoding, and VAAPI decoding with both VAAPI render method on and off. I have not tested VDPAU or OSX.

### CODE REVIEW

**Comment by laurimyllari** [comment]
Tagging @fritsch too. I hope the performance is ok - I can try to optimize the 1 pass rendering to full range RGB if needed by moving the luminance scaling back to YUV2RGB as a special case. If it's not needed, I suggest it leaving as is for now for simplicity since I'd like to do more changes to the rendering.

**Comment by fritsch** [comment]
Tested: 720p50 + Lanczos3, 576i50 with Lanczos3 and 1080i50 and as well 4k60p ... no skips no drops, performance wise it's the same as before.

I enabled Dithering and had the Dithering Depth on 8 (which was btw. the default).

My Gui setting is Use Limited Range.

Did I choose something by accident to bypass your code? If not -> all fine from my side. Btw. do you have a hint, content that I could use to see the difference quite good? After yesterdays NV12 commits - I cannot really distinguish between "perfect" and "perfect" :-)

**Comment by FernetMenta** [comment]
@fritsch can you test with this dropped: https://github.com/FernetMenta/xbmc/commit/8e3481bcc11e4501203386add12daab904edc473

**Comment by fritsch** [comment]
Same :-) works as expected. Btw. I did not understand the referenced commit anyways. As it seems to confuse my linear algebra knowledge :-)

**Comment by FernetMenta** [comment]
@laurimyllari could you rebase please. my last commit was wrong, somehow my system was in a bad state. seems my brain too yesterday evening :)

**Comment by fritsch** [comment]
I rebased it and added it ontop of an OpenELEC build. It has no performance impact. Succesfully running it with my test samples. Btw. I organized some testing, here:  http://forum.kodi.tv/showthread.php?tid=165707&pid=2039320#pid2039320

**Comment by laurimyllari** [comment]
> Did I choose something by accident to bypass your code? If not -> all fine from my side.

Thanks, sounds good. If you want to make dithering is enabled with your settings, drop the dither bit depth to something like 4 and you can see it applied.

I use a low depth to also check that it is applied before scaling (dither pattern is made up of display pixel sized pixels).

> Btw. do you have a hint, content that I could use to see the difference quite good? After yesterdays NV12 commits - I cannot really distinguish between "perfect" and "perfect" :-)

If you're using limited range output, there should be no difference now. If you use PC range, try the AVSHD709 pattern "Misc Patterns/A - Additional/1-Grayscale Ramp .mp4" (you can download the MP4 patterns at http://w6rz.net/avshd709/MP4-2c.7z). Some people recommend Ratatouille as a banding torture test (night time scene by the river) - I haven't tried it yet.

I guess scaling might benefit from the better precision even with limited range RGB, but I haven't tried that. Resolution test patterns in SD (upscaled to HD) might show something. I'd like to have gamma correct scaling later on, but that'll need higher FBO bit depth.

**Comment by laurimyllari** [comment]
@FernetMenta I rebased to your current EGL branch

**Comment by fritsch** [comment]
@laurimyllari I think we need to extend the description text user gets presented in the menus. I also only understand the bits as "full depth" after I tried 2 or 4. Also one line about the "general" use case that everybody can understand would be nice.

**Comment by fritsch** [comment]
I think normal user won't understand it anyways :-( sadly, therefore we need something that makes clear which values he should prefer. In that case you already set the 8 as preselected value which makes perfect sense. 

I also think of limiting this range to 6,7.8 only - as 2,3,4,5 only make sense for academic usecases, very special cases that produce the counter effect a average joe wants to see with his content.

**Comment by laurimyllari** [comment]
@fritsch let me know how you feel about these descriptions. I tried to make the recommended settings clear but still keep enough information for power users.

I agree on limiting the range to 6-8 but would like to keep the lower available until it's been tested more.

I've set the defaults to dithering enabled and 8bit output since those should give the best results for almost everyone. I also made them expert level settings since they can be safely ignored if the dithering works (if not, I'll need to fix it) and the performance is not an issue (I think it'll be fine on any GLSL system).

**Comment by fritsch** [comment]
Well done! An "r" is missing in the first comment, but it's fine that way.

Perhaps disabling it automatically when Limited Range is selected?

**Comment by FernetMenta** [comment]
should I press the button?

**Comment by fritsch** [comment]
Yes. This change is fine and needs wide testing. It will improve your way of watching TV :-) As you use both Full RGB ;-) Set dithering to 8 and make a blind test with the family :p

**Pull request merged**
