### PR TITLE
AdjustRefreshrate: Switch to higher resolution depending on source dims

### PR DESCRIPTION
**Pull request by fritsch**
v2: Unify logging

As discussed via mail and here: https://github.com/fritsch/xbmc/commit/445caa88d588fe437641c04aed59c126f9ee7e80#commitcomment-13195971

Any suggestions? Would be thankful for a short review.

### CODE REVIEW

**Comment by fritsch** [comment]
Let's wait for the user reports here: http://forum.kodi.tv/showthread.php?tid=231955&pid=2103879#pid2103879

No hurry.

**Comment by fritsch** [comment]
Okay - I am fine with how the code works - it was tested by fab67 on the forums.

I asked @paxxi and @bobo1on1 to review a bit on IRC and explained how it works - still happy after explaining.

Let's stand it here until monday.

**Comment by FernetMenta** [comment]
great! do you want me to press the button?

**Comment by fritsch** [comment]
We are not in a hurry. Let's wait for more reports. Btw. I can PR this to mainline directly if we think this is the way to go. One less for you to carry.

**Comment by FernetMenta** [comment]
you submitted to mainline

**Pull request closed without merging**
