### PR TITLE
AE: minors and WIP

### PR DESCRIPTION
**Pull request by fritsch**
EAC3 is currently not testable - seems the settings are confused somehow with the new format. At least it compiles again. I will pick it up again and retest EAC3

AC3 was working with the transcoder.

### CODE REVIEW

**Comment by fritsch** [comment]
The changes kind of suck - I now need to differ between the iec struct and the normal struct and set the values accordingly ... that fills the sink code with a whole lof of if elses ...

**Comment by fritsch** [comment]
Wait ! passthrough is not usable at all currently :-(

**Comment by FernetMenta** [comment]
I know, this is why this branch called "wip". I removed iec packing from decoding stage. raw packets need to find its way through ae to ActiveAESink. that will ask the sink whether it prefers raw or iec and will prepare data accordingly.

**Comment by fritsch** [comment]
Okay - I will add another commit in a minute where I asked some questions in the comments.

**Pull request merged**
