### PR TITLE
[cmake] More work on OSX

### PR DESCRIPTION
**Pull request by fetzerch**
Most noticable change for this PR: `kodi.bin` starts on OSX (out of source build with Makefile generator).
Big thanks to @Memphiz who wrote the parts for the wraplibs in 1ddd7bb.

Next steps:
The generated Xcode project still fails to build `kodi.bin` and the `DllPaths_generated.h` are still empty (should be fixed once find_soname is adapted to for clang). Also some files still have to be copied to the binary dir (preflight and XBMChelper).

@notspiff: Do you have an idea on how to implement `find_soname` using clang? Can you help explaining why it's implemented with this dummy compilation on linux? Couldn't that just be replaced by `find_library` for libs where we have find modules and `TARGET_FILE` expressions when the lib is built with the project?

### CODE REVIEW

**Comment by notspiff** [comment]
it's because we need the *actual* soname, i.e. libfoo.so.1.2.3 and not libfoo.so.

we are not linking to these libraries, and thus the normal symlink trick for the linker (having a libfoo.so that links to libfoo.so.1.2.3 in the -dev package) doesn't help us. we do not want to force users to install the -dev package (which is what contains the symlink), and thus we need to know the fully qualified so name, at configure time so we can record this in the code implementing the dynloading.

i'm not sure how far down the rabbit hole the TARGET_FILE expression goes, but i have a feeling it also stops at the symlink.

i assume you mean how to do this on osx, not how to do this with clang (as the current code works just fine with clang on linux for me). i think you mean how to implement it on osx. you have to replace the ldd usage with some otool magic, ref https://github.com/xbmc/xbmc/blob/master/configure.ac#L88

**Comment by wsnipex** [comment]
TARGET_FILE gives us the full real lib. We use it https://github.com/xbmc/xbmc/blob/master/project/cmake/scripts/common/addon-helpers.cmake#L48-L55 for filling in binary addons.xml

**Comment by wsnipex** [comment]
ah, sorry for the noise. This is not the same use case. We're building a lib, while you need to resolve an existing one for the find_soname case.

**Comment by notspiff** [comment]
Question is does it do that for imported targets. It makes sense it would
do that for generated targets only.
25. jan. 2016 16:42 skrev "Wolfgang Schupp" <notifications@github.com>:

**Comment by wsnipex** [comment]
yep, I already realized that.
Since we always build all depends ourselves on OSX, find_soname has access to the .so symlink and can therefore simply resolve it via readlink or something.

**Comment by notspiff** [comment]
i can't see a reason to invent something else than what is currently done in configure really (see link further up).

**Comment by Memphiz** [comment]
me neither - its all there already - just needs to be shuffled into that macros.cmake script

**Comment by fetzerch** [comment]
Yep, I agree it's best to use what is currently in place. Could have looked it up myself, sry.
The explanation is nevertheless really helpful for me. I'd like to know also how things work behind the scene. So thx for that.

@wsnipex: You can use https://cmake.org/cmake/help/latest/command/get_filename_component.html with `REALPATH` to resolve symlinks.

**Pull request merged**
