### PR TITLE
Vsync fixes for pi

### PR DESCRIPTION
**Pull request by popcornmix**
There may be a better place for the cmake hack, but this makes it build.

### CODE REVIEW

**Comment by hudokkow** [comment]
Don't worry, CMake changes look good. ;)

**Comment by FernetMenta** [comment]
no they don't look good at all. pi builds have to ignore everything in folder x11

**Comment by hudokkow** [comment]
Than this is not the right place. cmake/treedata is.

**Comment by FernetMenta** [comment]
right, X11 is not an option. either you want to build for X11 or not. Actually X11 is a target like Android or Pi. I already talked to @fetzerch about a solution.

**Pull request merged**
