### PR TITLE
Refactor builtins

### PR DESCRIPTION
**Pull request by notspiff**
This
- makes CBuiltins a singleton
- refactors the methods into several files

only autotools is updated.

### CODE REVIEW

**Comment by FernetMenta** [comment]
@notspiff I tried to rebase but struggling with https://github.com/xbmc/xbmc/commit/6219b4604670cdba8d27b96be2dc4bfbc0156d10
could you rebase please?

**Comment by notspiff** [comment]
rebased

**Comment by FernetMenta** [comment]
thank you very much

**Comment by FernetMenta** [comment]
@notspiff coverity complains about out-of bounds:
https://github.com/xbmc/xbmc/blob/943c92e494ffd35dab79eed810b15f5fb779f342/xbmc/dialogs/GUIDialogNumeric.cpp#L723
string is casted to void pointer in GetOutput
looks strange. do you have an idea?

**Comment by notspiff** [comment]
it's casting the string ptr to a void ptr. it is only given a string if
type is INPUT_NUMBER or INPUT_PASSWORD.

coverity cannot pick up on the latter fact since in theory type may be
another and then it would fail.

On Sun, Sep 13, 2015 at 11:56 AM, Rainer Hochecker <notifications@github.com

**Comment by FernetMenta** [comment]
thanks for this info. @fritsch, so nothing we need to worry about.

**Comment by fritsch** [comment]
Yeah @notspiff answered my mail that morning.

**Pull request closed without merging**
