### PR TITLE
fixup! have ServiceBroker return a pointer for WinSystem

### PR DESCRIPTION
**Pull request by Rechi**
compile tested for
- android
- ios
- linux (gbm, wayland & x11)
- osx
- windows (desktop & uwp)

I don't have setup a rbpi a toolchain.

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks. last time I squashed your changes into mine. now I did it vice verse. means that you are the author of the commit. hope this is ok for you

**Comment by Rechi** [comment]
I don't care abot the authorship as you are the person who knows how to fix it, if something is broken.

**Comment by FernetMenta** [comment]
but you don't mind if I keep you for the author, right?

**Comment by Rechi** [comment]
Keep it like you have done it now.
Just saying I didn't do much for it, only replaced some `&` with `*` and `.` with `->` to get it compiled.

**Pull request merged**
