### PR TITLE
add first cmake cross-compiled platform: raspberry-pi

### PR DESCRIPTION
**Pull request by wsnipex**
its probably not yet perfect, but it successfully compiles RPI.
I really don't have a setup to runtime test this atm, so I hoped @popcornmix or someone else could give it a shot.

This also includes (a few) cmake syncs needed for current master.

### CODE REVIEW

**Comment by FernetMenta** [comment]
can I squash all the cmake commits?

**Comment by wsnipex** [comment]
you can squash those to "rpi support" or something if you prefer. It'll will get rather big though.

**Comment by popcornmix** [comment]
What command did you run to build? I can test if you tell me how.
Any dependencies needed (apart from cmake)?

**Comment by wsnipex** [comment]
you build depends as before(you can skip ffmpeg in depends), then in tools/depends/target/xbmc:
make -f Makefile.cmake
After that you might need to run make install in the build dir. I think I forgot to add that to the makefile.

**Comment by popcornmix** [comment]
console: http://pastebin.com/MuX6vbwU
log: http://paste.ubuntu.com/12530760/

**Comment by wsnipex** [comment]
interesting. Do you have 
/opt/xbmc-dbg/arm-linux-gnueabihf/lib/pkgconfig/sqlite3.pc
and 
/opt/xbmc-dbg/arm-linux-gnueabihf/lib/libsqlite3.a

please do 
grep SQLITE CMakeCache.txt

**Comment by popcornmix** [comment]
```
dc4@dc4-XPS13-9333:~/xbmc_holder/xbmc/tools/depends/target/xbmc$ ls -l /opt/xbmc-dbg/arm-linux-gnueabihf/lib/pkgconfig/sqlite3.pc
-rw-r--r-- 1 dc4 dc4 290 Sep 22 23:34 /opt/xbmc-dbg/arm-linux-gnueabihf/lib/pkgconfig/sqlite3.pc
dc4@dc4-XPS13-9333:~/xbmc_holder/xbmc/tools/depends/target/xbmc$ ls -l /opt/xbmc-dbg/arm-linux-gnueabihf/lib/libsqlite3.a
-rw-r--r-- 1 dc4 dc4 1043866 Sep 22 23:34 /opt/xbmc-dbg/arm-linux-gnueabihf/lib/libsqlite3.a
dc4@dc4-XPS13-9333:~/xbmc_holder/xbmc/tools/depends/target/xbmc$ grep SQLITE arm-linux-gnueabihf/CMakeCache.txt
SQLITE3_CFLAGS:INTERNAL=
SQLITE3_CFLAGS_I:INTERNAL=
SQLITE3_CFLAGS_OTHER:INTERNAL=
SQLITE3_FOUND:INTERNAL=
SQLITE3_INCLUDEDIR:INTERNAL=
SQLITE3_LIBDIR:INTERNAL=
SQLITE3_LIBS:INTERNAL=
SQLITE3_LIBS_L:INTERNAL=
SQLITE3_LIBS_OTHER:INTERNAL=
SQLITE3_LIBS_PATHS:INTERNAL=
SQLITE3_PREFIX:INTERNAL=
SQLITE3_STATIC_CFLAGS:INTERNAL=
SQLITE3_STATIC_CFLAGS_I:INTERNAL=
SQLITE3_STATIC_CFLAGS_OTHER:INTERNAL=
SQLITE3_STATIC_LIBDIR:INTERNAL=
SQLITE3_STATIC_LIBS:INTERNAL=
SQLITE3_STATIC_LIBS_L:INTERNAL=
SQLITE3_STATIC_LIBS_OTHER:INTERNAL=
SQLITE3_STATIC_LIBS_PATHS:INTERNAL=
SQLITE3_VERSION:INTERNAL=
SQLITE3_sqlite3_INCLUDEDIR:INTERNAL=
SQLITE3_sqlite3_LIBDIR:INTERNAL=
SQLITE3_sqlite3_PREFIX:INTERNAL=
SQLITE3_sqlite3_VERSION:INTERNAL=
__pkg_config_checked_SQLITE3:INTERNAL=1
```

**Comment by wsnipex** [comment]
could you add this patch: http://paste.ubuntu.com/12531020/

looks like this for me:
>-- checking for module 'sqlite3'
--   found sqlite3, version 3.8.6
-- PKG_CONFIG_FOUND - SQLITE3_INCLUDE_DIRS: /opt/bcm-rootfs/arm-linux-gnueabihf/include;/opt/bcm-rootfs/arm-linux-gnueabihf/include SQLITE3_INCLUDEDIR: /opt/bcm-rootfs/arm-linux-gnueabihf/include SQLITE3_LIBRARIES: sqlite3;dl;pthread
-- Found Sqlite3: /opt/bcm-rootfs/arm-linux-gnueabihf/include;/opt/bcm-rootfs/arm-linux-gnueabihf/include

**Comment by popcornmix** [comment]
```-- PKG_CONFIG_FOUND - SQLITE3_INCLUDE_DIRS:  SQLITE3_INCLUDEDIR:  SQLITE3_LIBRARIES: 
```
http://pastebin.com/56ZXGcyS

**Comment by wsnipex** [comment]
please pastebin your /opt/xbmc-dbg/arm-linux-gnueabihf/share/Toolchain.cmake

**Comment by popcornmix** [comment]
http://paste.ubuntu.com/12531141/

**Comment by wsnipex** [comment]
your toolchain is missing all the cmake changes. Please reconfigure depends. (no need to rebuild though)

**Comment by popcornmix** [comment]
Some issue with directories requiring cleaning:
http://pastebin.com/HKAfhkav
http://paste.ubuntu.com/12535446/

**Comment by wsnipex** [comment]
yes, thats expected. Your kodi_src/lib needs a git clean -xfd to get rid of the autotools stuff created during previous configure runs.

Cmake won't "pollute" src trees as autotools does, since its designed for out of tree builds.

**Comment by popcornmix** [comment]
Did a ``git clean -xfd lib``, but seems libs are not configured:
http://pastebin.com/Z5KNihJP
http://paste.ubuntu.com/12542635/

**Comment by wsnipex** [comment]
its probably cached. please delete the build folder or at least CMakeCache.txt

**Comment by popcornmix** [comment]
I've done:
``rm -rf tools/depends/target/xbmc/arm-linux-gnueabihf/build/``
but no change:
http://pastebin.com/UAFx9TM6
http://paste.ubuntu.com/12545160/

**Comment by wsnipex** [comment]
sorry, I wasn't specific enough. I meant either delete tools/depends/xbmc/arm-linux-gnueabihf/CMakeCache.txt or the whole arm-linux-gnueabihf dir.

**Comment by popcornmix** [comment]
http://pastebin.com/L1A75XxL
http://paste.ubuntu.com/12545539/

**Comment by wsnipex** [comment]
first link is unavailable

**Comment by popcornmix** [comment]
http://xbmclogs.com/pwed7nhxr
http://paste.ubuntu.com/12640093

**Comment by wsnipex** [comment]
configure: error: source directory already configured; run "make distclean" there first
I don't see which lib it is, but its always the same reason. Best would be a complete git clean -xfd

**Comment by popcornmix** [comment]
After:
```
    $ git clean -xfd 
    $ cd xbmc/tools/depends
    $ ./bootstrap
    PATH="$PATH:/opt/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin" \
       ./configure --host=arm-linux-gnueabihf \
       --prefix=/opt/xbmc-bcm/xbmc-dbg \
       --with-toolchain=/usr/local/bcm-gcc/arm-bcm2708hardfp-linux-gnueabi/sysroot \
       --with-firmware=/opt/bcm-rootfs \
       --with-platform=raspberry-pi \
       --build=i686-linux

    $ make
    $ cd ../..
    $ make -C tools/depends/target/xbmc/ -f Makefile.cmake
```

http://xbmclogs.com/pbjzvo0cr
http://paste.ubuntu.com/12652084/

**Pull request merged**
