### PR TITLE
sync cmake buildsystem

### PR DESCRIPTION
**Pull request by notspiff**

### CODE REVIEW

**Comment by wsnipex** [comment]
independent of this, parallel builds are once again broken.
I'm getting tons of:
>[ 42%] Building CXX object build/settings/CMakeFiles/settings.dir/Settings.cpp.o
/opt/src/xbmc/xbmc/settings/DisplaySettings.cpp: In member function ‘virtual bool CDisplaySettings::OnSettingChanging(const CSetting*)’:
/opt/src/xbmc/xbmc/settings/DisplaySettings.cpp:278:5: error: ‘g_Windowing’ was not declared in this scope
     g_Windowing.UpdateResolutions();
     ^
/opt/src/xbmc/xbmc/settings/DisplaySettings.cpp: In member function ‘void CDisplaySettings::SetCurrentResolution(RESOLUTION, bool)’:
/opt/src/xbmc/xbmc/settings/DisplaySettings.cpp:361:36: error: ‘g_Windowing’ was not declared in this scope
   if (resolution == RES_WINDOW && !g_Windowing.CanDoWindowed())
                                    ^
/opt/src/xbmc/xbmc/settings/DisplaySettings.cpp: In static member function ‘static RESOLUTION CDisplaySettings::GetResolutionForScreen()’:
/opt/src/xbmc/xbmc/settings/DisplaySettings.cpp:622:25: error: ‘g_Windowing’ was not declared in this scope
   for (int idx=0; idx < g_Windowing.GetNumScreens(); idx++)
 

any idea which depends are missing?

**Comment by notspiff** [comment]
that shouldn't be a dependency thing, but a missing include. something is using g_Windowing without including the necessary header.

it could be a missing define which means we end up with no implementation included.

**Comment by wsnipex** [comment]
hmm, I've first noticed this on externalplayer while working on getting RPI building with cmake. Now I have it on native x86 as well. Since I have zero clue about the windowing stuff, it'd be thankful for any pointers

**Comment by notspiff** [comment]
see windowing/WindowingFactory.h

either that file is not being included somewhere, or none of those if conditions are satisfied.

**Comment by notspiff** [comment]
as for rpi a lot of gles / egl stuff will need adding. and likely quite a few defines.

**Comment by wsnipex** [comment]
thanks for that hint. I disabled X11 by default during rpi testing, which broken x86

**Comment by wsnipex** [comment]
@notspiff sorry for off topic here, but I don't get this:
http://pastebin.com/wCn5Nm5a
HAS_GL is not defined, HAS_GLES=2 is..

**Comment by notspiff** [comment]
system.h l134
14. sep. 2015 20:25 skrev "Wolfgang Schupp" <notifications@github.com>:

**Comment by FernetMenta** [comment]
@notspiff @wsnipex anything missing here or ready to merge?

**Comment by notspiff** [comment]
This is ready. wsnipex just occupied the space;)
15. sep. 2015 19:44 skrev "Rainer Hochecker" <notifications@github.com>:

**Comment by FernetMenta** [comment]
thanks.

**Pull request merged**
