### PR TITLE
[cmake-RFC] Modernize CMake usage

### PR DESCRIPTION
**Pull request by fetzerch**
@FernetMenta, @wsnipex: Not sure if this is the right place to discuss, but i thought it would be good to show some code to explain it a bit. Feel free to ignore, if that has been discussed already and was rejected.

This is a suggestion / RFC to modernize the CMake usage in Kodi's CMake build system. Mostly this is about letting (external) targets specify their own usage requirements such as include directories or compile options. Targets that use other targets then just need to use the target_link_libraries command and don't have to use include_directories or add_definitions. Which if I'm not mistaken would
simplify the current build system a lot and makes some of the own built macros obsolete.

Disadvantages:
- Needs "modern" CMake versions (2.8.12 or later).

Advantages:
- The user of a library doesn't have to know what includes or
  definitions are necessary. (I know this is already wrapped in macros
  in the current version).
- Less macro magic, more plain CMake (easier to understand for people
  who know CMake but not the Kodi macros).
  Also no need to propagate variables due to transitive dependencies.
- External libraries are linked to the Kodi target that needs them.
- No need to use include_directories() any more which is error prone
  (because it might set too many unneeded includes in sub directories).
- Typos in the library of target_link_libraries will show a warning
  (CMake knows that targets with "::" are CMake targets and hence it
   does not fall back to linking -lnamewithtypo which would result in
   linker errors).
- Typos in the module variables (e.g. MYSQLCLIENT_LIBRARIES) are
  directly recognized, as as set_target_properties will fail.
- The include directories of imported target is automatically
  recognized as system includes (on supported platforms compilers will
  not issue library header warnings and will not scan such headers for
  recompilation).

References (as the CMake documentation is not very beginner friendly):
- http://www.steveire.com/WhatWhyHowCMake.pdf
- http://www.slideshare.net/DanielPfeifer1/cmake-48475415

### CODE REVIEW

**Comment by FernetMenta** [comment]
@notspiff ping

**Comment by notspiff** [comment]
sorry for late response. i actually want to require cmake 3.x myself for various reasons, so the disadvantage is gonna be out-disadvantaged ;)

it looks all good to me. as you point out the cmake documentation is not the easiest at times and since i to a large extent learnt things as i developed the build system, some best pratices may have been missed.

**Comment by fetzerch** [comment]
@notspiff: Great, thanks. From my experience CMake really added some nice and useful features in the last versions that can simplify things quite a bit. And yes it's much learning by doing.As as soon as it It's been just a few days ago, when I discovered the new version of the module documentation at https://cmake.org/cmake/help/v3.4/manual/cmake-developer.7.html#a-sample-find-module. So far I just knew the outdated old wiki page.

Since your wrote a big part of the CMake files (if not all), I hope it's ok if I ask some questions in the next days. I do have some difficulties understanding for example the core_link_library and the wrappers libraries. Should I ask on github? mail? irc?

Cheers, Christian

**Comment by notspiff** [comment]
Mail / hub is the easiest. Noninteractivity is a good thing in the context.
And i dont mind at all, just happy for the help.

I am guessing that you are wondering about the wrapping things. Windows
runtime injects those symbols instead of replacing using linker maps. So
most of core_link_library is void on windows. In fact it is almost void on
linux as well these days as most wrapped libraries have been removed /
replaced.
6. jan. 2016 00:36 skrev "Christian Fetzer" <notifications@github.com>:

**Comment by fetzerch** [comment]
Ok, that answeres indeed already a big question :-). Now that you mentioned abandoned libraries: do you have a list of what is removed or replaced? That would help and eventually prevent me from doing useless work (for example in the find modules if a lib gets removed).

**Comment by notspiff** [comment]
if things have been removed you don't really see them. but i have been
rebasing this thing for over 2 years, so cruft has built up in the macros.
i have removed unused find modules (no guarantee it's 100% but it should be
close) over time though. many of them won't be relevant on windows so i
wouldn't attack them file by file, but rather issue by issue. that way you
won't change files unnecessarily.

**Comment by fetzerch** [comment]
This can be closed now as well.

**Pull request closed without merging**
