### PR TITLE
[RFC] Multi video streams

### PR DESCRIPTION
**Pull request by ace20022**
Hacked on the fly, but it seems to work (only tested one sample).

### CODE REVIEW

**Comment by ace20022** [comment]
Why merged? It wasn't complete and the tmp commit was only for compile reasons. I wanted to know if it's ok feature wise

**Comment by FernetMenta** [comment]
ahh, you did not mention. imo this is ok, at least for this dev branch. regarding the tmp commit, there's going to be more work when pull the work from aewip branch.

**Comment by ace20022** [comment]
Yes, my pr description are usually minimal. How does this dev branch work? How do you "build" a final pr against kodi master? The hopefully feature complete commit for this pr is at: https://github.com/ace20022/xbmc/commit/6156289773e4f67967a644416688d7a283d96b16

**Comment by FernetMenta** [comment]
do you want me to swap commits?

> How do you "build" a final pr against kodi master?

good question. I think self contained commits like yours will stay as is. Other parts I am working on have become unsquashable (my branch is ahead of master by 144 commits). I need to restructure the work. Going to be fun :)

**Comment by ace20022** [comment]
> do you want me to swap commits?

that would be great

> Going to be fun :)

yes ;)

**Pull request merged**
