### PR TITLE
[cmake] More work on Windows support

### PR DESCRIPTION
**Pull request by fetzerch**
Builds now also with the Visual Studio generator (due to b29fa51).

### CODE REVIEW

**Comment by wsnipex** [comment]
great!  wanted to say thanks for the awesome work you did here.

**Comment by fetzerch** [comment]
It's been mostly fun and I really hope we can get it in the shape for including it in the mainline :-).
But since vacation is over now, the next changes will come in a bit less frequently.

One thing I wanted to ask: Meanwhile quite a big number of TODOs have piled up (currently only on an "analog" notepad). I think it would be a good idea if we collect those somewhere where it's available for anyone who might want to join the fun. We could combine that also with stuff that needs to be done for other platforms and also for the dependencies. Do you in the Team use a tool for this which we could share? Would probably be good to also note down priorities so that we can focus on what is needed for mainline integration and do less prio tasks later.

**Comment by FernetMenta** [comment]
Unfortunately we don't have a proper tool for this. I would create a thread in the development section on the forum.

**Comment by fetzerch** [comment]
Ack: http://forum.kodi.tv/showthread.php?tid=255893

**Pull request merged**
