### PR TITLE
AdjustRefreshrate: Introduce setting

### PR DESCRIPTION
**Pull request by fritsch**
This is based on your latest WIP so that you don't have to rebase that one in ...

Keep it open for now please, still waiting for forum users not posting their logs (which had issues with their AVR switching to non supported resolutions it announced itself :-()

### CODE REVIEW

**Comment by FernetMenta** [comment]
rather than disabling it it should be made work on those systems. this can be done by white or blacklisting resolotions.

**Comment by fritsch** [comment]
Let's wait on this debuglog. I think the AVR will just add all resolutions it knows, which might include resolutions we normally want to honnor.

Btw. What are we doing with users that have a TV which's 1080p mode is broken (or an AVR that can really only support 720p) and so they run in 720p? Everytime they adjust refreshrate we would switch away to 1080p ...

**Comment by fritsch** [comment]
http://paste.ubuntu.com/12464971/ <- I have such a beast myself I just found out :-)

See the 2880x480 mode

**Comment by fritsch** [comment]
^^ that would be too easy :-) but let's see.

**Comment by fritsch** [comment]
I will PR that fix up to mainline ... then let's see if we still need such a setting.

**Comment by fritsch** [comment]
See: https://github.com/fritsch/xbmc/commit/4c14e8d2ef8ae9f09fa448e736eb6781e19e3dfb

**Pull request closed without merging**
