### PR TITLE
Fernet master

### PR DESCRIPTION
**Pull request by wsnipex**
cmake fixes. With those build succeeds on linux.
@notspiff: maybe something useful for you there, e.g. ffmpeg parallel building

### CODE REVIEW

**Comment by FernetMenta** [comment]
something is going wrong here: http://paste.ubuntu.com/12338718/
any idea?

**Comment by wsnipex** [comment]
not sure, seems threads is not found.
I've just fixed 2 other issues: top 2 commits: https://github.com/wsnipex/xbmc/commits/fernet-master

worth a try if it fixes your issue as well, but they are needed anyway.

**Comment by wsnipex** [comment]
ah: Determining if the function CRYPTO_set_locking_callback exists failed with the following output:
Change Dir: /home/xbmc/progs/src/xbmc/build/CMakeFiles/CMakeTmp

Thats something we do to check if openssl was built static iirc

**Comment by wsnipex** [comment]
here: https://github.com/FernetMenta/xbmc/blob/master/project/cmake/modules/FindCurl.cmake#L25

**Comment by wsnipex** [comment]
to continue the spam: on a normal linux distro that uses curl from system package, this test will fail. This is perfectly normal as openssl is not linked static to curl. This check exists mostly for unified depends builds.

**Comment by FernetMenta** [comment]
this is greak to me :) can you reproduce the issue? do you want me anything to try?

**Comment by FernetMenta** [comment]
````
CMake Error at /home/xbmc/progs/src/xbmc/tools/depends/native/TexturePacker/CMakeLists.txt:29 (list):
  list GET given empty list
```

**Comment by wsnipex** [comment]
as for the original issue: no I cannot reproduce. Can you provide the normal cmake output?
And for the Texturepacker issue plz a log as well. I have not tested it against gflib4, but v5 should now be detected properly.

**Pull request merged**
